<template>
  <aside class="agent-panel side-panel" aria-label="Media assistant" @keydown.stop>
    <header class="agent-header"><h3>Assistant</h3><button class="agent-icon" title="New chat" aria-label="New chat" :disabled="busy" @click="agent.newChat">＋</button><button class="agent-icon" title="Close assistant" aria-label="Close assistant" :disabled="busy" @click="agent.toggle">×</button></header>
    <nav v-if="!viewer" class="agent-modes" aria-label="Assistant mode"><button :class="{ active: s.mode === 'search' }" :disabled="busy" @click="s.mode = 'search'">Find media</button><button :class="{ active: s.mode !== 'search' }" :disabled="busy" @click="s.mode = 'chat'">Selected items</button></nav>
    <div ref="conversation" class="agent-conversation" @scroll="trackScroll">
      <div v-if="!visibleMessages.length && (!s.results || s.mode !== 'search') && !busy && !visibleProposals.length" class="agent-empty"><p>{{ s.mode === 'search' ? 'What would you like to find?' : 'What would you like to know?' }}</p><button v-for="suggestion in suggestions" :key="suggestion" class="agent-suggestion" @click="fill(suggestion)">{{ suggestion }}</button></div>
      <template v-for="(message, index) in visibleMessages" :key="index"><p v-if="index === 0 || message.runId !== visibleMessages[index - 1].runId" class="agent-user">{{ message.question }}</p><p v-if="agent.getMediaIds().length > 1" class="agent-muted">{{ mediaLabel(message.mediaId) }}</p><AgentMarkdown class="agent-answer" :content="message.answer || 'Suggested changes are ready to review.'" /></template>
      <template v-if="s.results && s.mode === 'search'"><p class="agent-user">{{ s.searchQuestion }}</p><p class="agent-muted">{{ s.results.results.length }} candidates</p>
          <div class="agent-row"><button class="btn" :disabled="!s.resultSelection.length" @click="agent.useResults('verify')">Analyze selected</button><button class="btn" :disabled="!s.resultSelection.length" @click="agent.useResults('chat')">Suggest changes</button></div><div v-for="group in resultGroups" :key="group.key"><h4>{{ group.label }}</h4><div v-for="result in group.items" :key="result.mediaId" class="agent-result-row"><input type="checkbox" v-model="s.resultSelection" :value="result.mediaId" aria-label="Select search candidate" /><button class="agent-result" @click="agent.openMedia(result.item)"><img v-if="result.item?.__thumbnailAvailable" :src="buildImageUrl(result.item.__thumbnailPath)" alt="" /><span>{{ result.item?.Customization?.Title || result.item?.FilePath }}</span></button><p v-if="result.verdict">{{ result.verdict.explanation }}</p></div></div>

        <button class="btn" :disabled="busy || s.depth >= 10000" @click="agent.search(true)">Find more</button>
      </template>
      <template v-if="s.running && s.activeQuestion && s.mode !== 'search' && !visibleMessages.some(message => message.runId === s.activeRunId)"><p class="agent-user">{{ s.activeQuestion }}</p></template>
      <div v-if="s.partialAnswer && agent.getMediaIds().includes(s.partialMediaId)" class="agent-answer"><AgentMarkdown :content="s.partialAnswer" /><small v-if="!s.running">Incomplete response</small></div>
      <p v-if="busy" class="agent-muted" role="status">{{ progressText }}</p>
        <article v-for="proposal in visibleProposals" :key="proposal.proposalId" class="agent-review"><h4>Suggested changes</h4><div v-for="(value, field) in proposal.patch" :key="field"><label><input type="checkbox" v-model="proposal.selectedFields" :value="field" :disabled="s.applying" /> {{ field }}</label><del>{{ displayField(field, proposal.before[field]) }}</del><template v-if="field === 'TagIds'"><label v-for="id in tagOptions(proposal)" :key="id"><input type="checkbox" v-model="proposal.patch.TagIds" :value="id" :disabled="s.applying || (!proposal.allowTagRemoval && proposal.before.TagIds.includes(id))" />{{ tags.getTagText(id) }}</label></template><textarea v-else v-model="proposal.patch[field]" class="input agent-edit" :maxlength="field === 'Title' ? 512 : 8000" :aria-label="'Reviewed ' + field" :disabled="s.applying" /><template v-if="viewer && draftConflicts(proposal, field)"><p>Current draft: {{ displayField(field, agent.getDraft(proposal.mediaId, field)) }}</p><label><input type="checkbox" v-model="proposal.overrideFields" :value="field" :disabled="s.applying" /> Replace my current draft value</label></template></div><button class="btn" :disabled="s.running || s.applying || !proposal.selectedFields.length" @click="agent.apply(proposal)">{{ viewer ? 'Use changes' : 'Apply changes' }}</button><button class="btn" :disabled="s.applying" @click="agent.discard(proposal)">Discard</button></article>
        <button v-if="!viewer && visibleProposals.length > 1" class="btn" :disabled="s.running || s.applying || !visibleProposals.some(item => item.selectedFields.length)" @click="agent.apply()">Apply all reviewed fields</button>

      <p v-if="viewer && visibleProposals.length" class="agent-muted">Use changes adds them to your draft. Save in the viewer when ready.</p>
      <p v-if="s.error" class="agent-error" role="alert">{{ s.error }}</p><p v-if="s.notice" class="agent-muted" role="status">{{ s.notice }}</p>
      <button v-if="s.remaining.length && !busy" class="btn" @click="agent.submit(true)">Continue {{ s.remaining.length }} remaining</button>
    </div>
    <form class="agent-composer" @submit.prevent="agent.submit()">
      <button type="button" class="agent-context" :disabled="busy" @click="contextOpen = !contextOpen"><img v-if="contextItem?.__thumbnailAvailable" :src="buildImageUrl(contextItem.__thumbnailPath)" alt="" /><span>{{ contextLabel }}</span><span aria-hidden="true">⌄</span></button>
      <div v-if="contextOpen" class="agent-context-list"><p v-if="s.mode === 'search'">{{ s.scope === 'library' ? 'Searching the entire library' : 'Searching within current gallery filters' }}</p><p v-for="id in agent.getMediaIds()" v-else :key="id">{{ mediaLabel(id) }}</p></div>
      <div class="agent-input-box"><textarea ref="input" v-model="s.query" class="agent-query" rows="2" maxlength="4000" :disabled="busy" :placeholder="s.mode === 'search' ? 'Describe what to find…' : 'Message Assistant…'" aria-label="Assistant message" @input="resize" @keydown="composerKey" />
        <div class="agent-composer-actions"><button ref="optionsButton" type="button" class="agent-icon" title="Options" aria-label="Message options" :aria-expanded="s.options" :disabled="busy" @click="s.options = !s.options"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 7h16M4 17h16M8 4v6M16 14v6" /></svg></button><span class="agent-muted">{{ s.mode === 'verify' ? 'Analyze selection' : '' }}</span><button v-if="s.running" type="button" class="agent-send" aria-label="Stop response" title="Stop" @click="agent.cancel">■</button><button v-else class="agent-send" type="submit" aria-label="Send message" title="Send" :disabled="busy || (s.mode !== 'verify' && !s.query.trim())">↑</button></div>
      </div>
      <div v-if="s.options" ref="options" class="agent-options" @keydown.esc.prevent="closeOptions">
        <p class="agent-muted">{{ providerLabel }}</p>
        <template v-if="s.mode === 'search'"><label>Search in<select v-model="s.scope" class="input"><option value="gallery">Current gallery filters</option><option value="library">Entire library</option></select></label><label><input type="checkbox" v-model="s.local" /> Search locally only</label><p class="agent-muted">{{ s.local ? 'Use English for visual queries. No network request.' : 'Only your search request goes to the provider.' }}</p><details><summary>Search details</summary><label><input type="checkbox" v-model="s.availableOnly" /> Use the available index without refreshing</label><pre v-if="s.results">{{ JSON.stringify(s.results.plan, null, 2) }}</pre><p v-if="s.results?.missingTextMedia">{{ s.results.missingTextMedia }} items need updated metadata embeddings.</p></details></template>
        <template v-else><details><summary>Shared context</summary><label v-for="group in metadataGroups" :key="group.value"><input type="checkbox" v-model="s.groups" :value="group.value" />{{ group.label }}</label><p class="agent-muted">Selected images or sampled video frames are included when you send.</p></details><details><summary>Tag changes</summary><p class="agent-muted">The assistant can look up existing tags for tagging requests.</p><label><input type="checkbox" v-model="s.replaceTags" /> Allow replacing or removing tags</label></details><button type="button" class="agent-menu-action" @click="agent.preview()">View shared context</button><div v-if="s.preview" class="agent-context-preview"><p>{{ s.preview.count }} items · {{ s.preview.destination?.model }}</p><p>{{ s.preview.destination?.baseUrl }}</p><p>{{ s.preview.groups.map(value => metadataGroups.find(group => group.value === value)?.label).join(', ') }}</p><p v-for="item in s.preview.items" :key="item.mediaId">{{ item.filePath }} · up to {{ item.frames }} images/frames</p></div></template>
        <button type="button" class="agent-menu-action" @click="s.settings = true; s.options = false">Assistant settings…</button>
      </div>
    </form>
    <AgentSettingsDialog v-if="s.settings" @close="s.settings = false" />
  </aside>
</template>
<script setup>
import { computed, inject, ref, watch, nextTick, onMounted, onBeforeUnmount } from 'vue';
import { AGENT_CONTEXT, TAG_CONTEXT } from '../context/renderer-contexts.js';
import { buildImageUrl } from '../domain/media-formatters.mjs';
import AgentSettingsDialog from './AgentSettingsDialog.vue';
import AgentMarkdown from './AgentMarkdown.vue';
defineProps({ viewer: Boolean });
const agent = inject(AGENT_CONTEXT), s = agent.state, tags = inject(TAG_CONTEXT);
const input = ref(null), conversation = ref(null), options = ref(null), optionsButton = ref(null), contextOpen = ref(false);
let followBottom = true;
const busy = computed(() => s.running || s.submitting || s.applying);
const displayField = (field, value) => field === 'TagIds' ? value.map(id => tags.getTagText(id)).join(', ') : value;
const tagOptions = proposal => [...new Set([...(proposal.before.TagIds || []), ...(proposal.reviewTagIds || proposal.patch.TagIds)])];
const draftConflicts = (proposal, field) => { const draft = agent.getDraft(proposal.mediaId, field); return draft !== undefined && JSON.stringify(draft) !== JSON.stringify(proposal.before[field]) && JSON.stringify(draft) !== JSON.stringify(proposal.patch[field]); };
const visibleMessages = computed(() => s.messages.filter(entry => agent.getMediaIds().includes(entry.mediaId)));
const visibleProposals = computed(() => s.proposals.filter(entry => agent.getMediaIds().includes(entry.mediaId)));
const metadataGroups = [{ value:'basic', label:'Basic information' }, { value:'location', label:'Location' }, { value:'people', label:'People' }, { value:'hidden', label:'Private notes' }, { value:'technical', label:'Technical details' }];
const mediaLabel = id => { const item = agent.getMediaItem(id); return item?.Customization?.Title || item?.FilePath || 'Selected item'; };
const contextItem = computed(() => agent.getMediaItem(agent.getMediaIds()[0]));
const contextLabel = computed(() => s.mode === 'search' ? (s.scope === 'library' ? 'Entire library' : 'Current gallery') : agent.getMediaIds().length === 1 ? mediaLabel(agent.getMediaIds()[0]) : agent.getMediaIds().length + ' selected items');
const providerLabel = computed(() => s.mode === 'search' && s.local ? 'On this computer' : s.status?.providers?.profiles?.find(profile => profile.role === (s.mode === 'search' ? 'conversation' : 'vision'))?.model || 'Configured provider');
const suggestions = computed(() => s.mode === 'search' ? ['Find sea scenery', 'Find photos of animals'] : [agent.getMediaIds().length > 1 ? 'Describe these items' : contextItem.value?.FileSystem?.FileType === 'video' ? 'Describe this video' : 'Describe this photo', 'Suggest tags', 'Improve the description']);
const progressText = computed(() => s.applying ? 'Applying changes…' : s.progress?.total && Number.isFinite(s.progress.completed) ? 'Analyzing ' + Math.min(s.progress.total, s.progress.completed + 1) + ' of ' + s.progress.total + '…' : s.mode === 'search' ? 'Searching your library…' : 'Thinking…');
const resultGroups = computed(() => { const items = new Map((s.results?.items || []).map(item => [item.MediaId,item])); return [['matches','Matches'],['metadata-supported','Supported by metadata'],['unknown','Unknown location or date'],['conflicts','Conflicting evidence'],['visual-candidates','Possible matches']].map(([key,label]) => ({ key,label,items:(s.results?.results || []).filter(result => result.group === key).map(result => ({ ...result,item:items.get(result.mediaId) })) })).filter(group => group.items.length); });
function resize() { if (input.value) { input.value.style.height = 'auto'; input.value.style.height = Math.min(160,input.value.scrollHeight) + 'px'; } }
function fill(text) { s.query = text; nextTick(() => { resize(); input.value?.focus(); }); }
function composerKey(event) { if (event.key === 'Enter' && !event.shiftKey && !event.isComposing && event.keyCode !== 229) { event.preventDefault(); agent.submit(); } }
function trackScroll() { const el = conversation.value; followBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 60; }
function closeOptions() { s.options = false; optionsButton.value?.focus(); }
function outside(event) { if (s.options && !options.value?.contains(event.target) && !optionsButton.value?.contains(event.target)) s.options = false; }
watch(() => [s.messages.length,s.partialAnswer,s.results,s.proposals.length,s.running], () => nextTick(() => { if (followBottom && conversation.value) conversation.value.scrollTop = conversation.value.scrollHeight; }));
watch(() => s.query, () => nextTick(resize));
onMounted(() => { document.addEventListener('pointerdown',outside); input.value?.focus(); });
onBeforeUnmount(() => document.removeEventListener('pointerdown',outside));
</script>
<style scoped>
.agent-panel { width:100%; height:100%; min-height:0; min-width:0; box-sizing:border-box; display:flex; flex-direction:column; overflow:hidden; padding:0; background:#fff; color:#23405a; }
.agent-input-box:focus-within { border-color:#80a4c7; box-shadow:0 0 0 1px #80a4c733; }.agent-query:focus-visible { outline:none; }
.agent-header { display:flex; align-items:center; gap:6px; padding:14px 18px; }.agent-header h3 { margin:0 auto 0 0; font-size:17px; }
.agent-icon { display:grid; place-items:center; width:32px; height:32px; border:0; border-radius:8px; background:transparent; color:inherit; font-size:23px; cursor:pointer; }.agent-icon:hover,.agent-modes button:hover { background:#f0f4f8; }button:disabled { opacity:.45; cursor:default; }button:focus-visible,textarea:focus-visible { outline:2px solid #5088bd; outline-offset:2px; }
.agent-modes { display:flex; gap:4px; padding:0 16px 10px; }.agent-modes button { border:0; border-radius:16px; padding:6px 12px; background:transparent; color:inherit; font:inherit; font-size:12px; }.agent-modes .active { background:#edf3f9; }
.agent-conversation { flex:1; min-height:0; overflow:auto; padding:12px 18px; overflow-wrap:anywhere; }.agent-empty { margin:35% 0 20px; text-align:center; }.agent-empty p { font-size:18px; }.agent-suggestion { display:block; margin:8px auto; border:1px solid #e1e7ed; background:white; border-radius:18px; padding:9px 14px; color:inherit; cursor:pointer; }
.agent-user { background:#eef3f8; border-radius:16px 16px 4px 16px; padding:10px 14px; margin:16px 0 14px auto; width:fit-content; max-width:90%; white-space:pre-wrap; font-size:14px; }.agent-answer { font-size:14px; line-height:1.65; white-space:normal; margin:10px 0 20px; }.agent-muted { font-size:12px; color:#738294; line-height:1.5; }.agent-error { color:#a33e3e; font-size:13px; }
.agent-composer { position:relative; flex:none; padding:8px 14px 14px; }.agent-context { display:flex; align-items:center; gap:6px; border:0; background:transparent; padding:5px 4px 9px; color:#6b7c8e; max-width:100%; cursor:pointer; font-size:12px; }.agent-context span:first-of-type { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.agent-context img { width:24px; height:24px; border-radius:4px; object-fit:cover; }.agent-input-box { border:1px solid #dce3eb; border-radius:18px; padding:10px; background:#fafbfd; }.agent-query { width:100%; box-sizing:border-box; border:0; outline:none; background:transparent; color:inherit; font:inherit; font-size:14px; line-height:1.5; resize:none; min-height:46px; max-height:160px; }.agent-composer-actions { display:flex; align-items:center; justify-content:space-between; gap:6px; }.agent-send { width:32px; height:32px; border-radius:50%; border:0; background:#244c71; color:white; font-size:21px; cursor:pointer; }
.agent-options { position:absolute; bottom:calc(100% - 30px); left:14px; right:14px; max-height:min(440px,60vh); overflow:auto; padding:14px; background:white; border:1px solid #dce3eb; border-radius:12px; box-shadow:0 8px 30px #243c5522; z-index:10; font-size:13px; }.agent-options label { display:block; margin:10px 0; }.agent-options select { display:block; width:100%; margin-top:6px; }.agent-options details { padding:9px 0; }.agent-options summary { cursor:pointer; }.agent-menu-action { display:block; width:100%; border:0; text-align:left; background:transparent; color:inherit; padding:10px 0; cursor:pointer; }.agent-options pre { white-space:pre-wrap; font-size:11px; }.agent-context-list,.agent-context-preview { max-height:160px; overflow:auto; font-size:12px; overflow-wrap:anywhere; }
.agent-review { border:1px solid #e0e6ed; border-radius:12px; padding:12px; margin:16px 0; font-size:13px; }.agent-review h4 { margin:0 0 12px; }.agent-review label { display:block; margin:8px 0; }.agent-review del { color:#917474; }.agent-edit { width:100%; box-sizing:border-box; min-height:60px; resize:vertical; font:inherit; }.agent-row { display:flex; flex-wrap:wrap; gap:6px; }.agent-result-row { display:flex; align-items:center; gap:6px; flex-wrap:wrap; }.agent-result { display:flex; flex:1; min-width:0; gap:8px; align-items:center; border:0; background:none; padding:7px 0; text-align:left; color:inherit; cursor:pointer; }.agent-result img { width:64px; height:48px; object-fit:cover; border-radius:6px; }.agent-result span { overflow-wrap:anywhere; font-size:13px; }.agent-result-row p { font-size:12px; }.btn { font-size:12px; }
</style>
